name: Publish Docker image
on:
  push:
    branches: 
      - master

jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Publish to Github Packages
        uses: docker/build-push-action@v0
        with:
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/next
          tags: latest, ${{ github.run_number }}      
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: BDADmitry/next
          tags: latest, ${{ github.run_number }}
