name: Build and Push docker image

on: [push]

env:
  DOCKER_FILE: "docker3.2.1/Dockerfile"
  REPO_NAME: "deman27/ubuntu-apache"
  DOCKER_USERNAME: "deman27"

jobs:

  build-and-push-docker-image:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Generate image tag
      run: echo "IMAGE_TAG=${{ env.DOCKER_USERNAME }}/$REPO_NAME:$GITHUB_SHA" >> $GITHUB_ENV;

    - name: Build image
      run: docker build --file ${DOCKER_FILE} --tag ${IMAGE_TAG}  .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image to Docker Hub
      run: |
        docker push ${IMAGE_TAG}
